# Site settings

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
email:
author:
description:

# Build settings
permalink: :title/
sass:
  sass_dir: css
